T346029 ES Module
wmde/wikibase-release-pipeline pull request #481
Opened 2023-09-26 16:26 UTC by RickiJay-WMDE

2023-09-28 14:30 UTC, rti requested changes
Great work!

2023-09-29 08:03 UTC, RickiJay-WMDE commented on test/suites/base__fedprops/base__fedprops.conf.js
> +import { deepmerge } from 'deepmerge-ts';
That does work, but `deepmerge-ts` is already a requirement of `@wdio/runner`, so we're already installing it.

2023-09-29 08:13 UTC, RickiJay-WMDE commented on test/suites/base__fedprops/base__fedprops.conf.js
> +import { deepmerge } from 'deepmerge-ts';
Would you still rather we use `lodash`?

2023-10-05 12:41 UTC, lorenjohnson approved these changes
LGTM! 🎉

2023-10-05 14:55 UTC, merged

2023-10-10 13:21 UTC, rti commented on test/suites/base__fedprops/base__fedprops.conf.js
> +import { deepmerge } from 'deepmerge-ts';
Sorry for not responding for a while.

Well, I still see a benefit in keeping our direct dependencies as low as possible. I would have opt'ed for using lodash instead. Anyway. Also happy that this is merged as is.