chore: bump version on main branch to not collide with release branches
wmde/wikibase-release-pipeline pull request #579
Opened 2024-02-14 10:28 UTC by rti

2024-02-14 12:27 UTC, RickiJay-WMDE approved these changes

2024-02-14 13:44 UTC, RickiJay-WMDE requested changes
Please update repo test for mediawiki version

2024-02-15 07:33 UTC, rti commented
@RickiJay-WMDE reverted the mediwiki version change, this should be really part of https://phabricator.wikimedia.org/T354644

What I really wanted to do was the suite version bump. Shouldn't have mixed it in the first place. Sorry for that.

2024-02-16 12:26 UTC, RickiJay-WMDE approved these changes

2024-02-19 07:18 UTC, merged