Cleanup II
wmde/wikibase-release-pipeline pull request #588
Opened 2024-02-26 13:44 UTC by RickiJay-WMDE

2024-02-26 13:46 UTC, rti submitted a review, later dismissed

2024-02-26 17:53 UTC, rti reviewed
Is this done by a linting script?

2024-02-26 17:54 UTC, rti commented on .github/workflows/_build_test.yml
> +          echo "hello world"
maybe we can have some explanation here why we add this noop step

2024-02-26 17:55 UTC, rti requested changes

2024-02-26 17:55 UTC, rti commented on .github/workflows/_build_test.yml
> +          echo "hello world"
```suggestion
      - run: true
```

2024-02-27 07:55 UTC, rti commented on .github/workflows/_build_test.yml
> +    # Post-test CI step - to check all tests succeeded
```suggestion
    # Post-test CI step - to check all tests succeeded
    # Github Branch Protection rules require this to pass to allow merging
```

2024-02-27 22:04 UTC, RickiJay-WMDE commented
> Is this done by a linting script?

Yeah - `prettier`, followed by `eslint`. Having trouble getting the latter to work on yml files, so I haven't added those to the script

2024-02-28 17:25 UTC, RickiJay-WMDE commented
> > Is this done by a linting script?
> 
> Yeah - `prettier`, followed by `eslint`. Having trouble getting the latter to work on yml files, so I haven't added those to the script in `package.json`

Update: Got YAML files working

2024-02-29 07:47 UTC, rti reviewed
Shouldn't prettier be installed automatically?

```
❱ ./lint.sh -f             
Fixing Linting and Formatting issues in Typescript
[+] Building 66.4s (15/15) FINISHED
=> naming to docker.io/library/wikibase-suite-test-runner-test-runner
Need to install the following packages:
prettier@3.2.5
Ok to proceed? (y) 
```

2024-02-29 07:49 UTC, rti commented
Question: do we lint from the project root now? Or is this another topic?

2024-03-01 13:11 UTC, RickiJay-WMDE commented
> Question: do we lint from the project root now? Or is this another topic?

I think that's another topic - we're still linting from `/test` here

2024-03-01 13:14 UTC, rti approved these changes

2024-03-01 13:18 UTC, merged