Cleanup III
wmde/wikibase-release-pipeline pull request #603
Opened 2024-03-05 15:00 UTC by RickiJay-WMDE

2024-03-19 08:27 UTC, rti requested changes
🚀🚀🚀

2024-03-19 10:30 UTC, RickiJay-WMDE commented on test/.eslintrc.json
> +	"ignorePatterns": [ "**/results/result.json", "!.github", "!example" ],
Exactly, yes

2024-03-19 10:32 UTC, RickiJay-WMDE commented on .github/reporter/report.js
> +	return;
It's a tab character - and I'm pretty sure you can customize how many spaces it appears as in github

2024-03-20 09:14 UTC, RickiJay-WMDE commented on lint.sh
> +    npx prettier \"**/*.{cjs,js,json,mjs,ts}\" --write \
The argument @lorenjohnson had for this was any Javascript elsewhere would be in its own Node project - which is true, the only other JS present is in `.github/reporter` - and therefore those projects should have their own linting. That one currently doesn't, admittedly.

2024-03-20 09:14 UTC, RickiJay-WMDE commented on lint.sh
> +  npx eslint . --ext .cjs,.js,.json,.mjs,.ts $ESLINT_FLAGS
See previous

2024-03-21 11:01 UTC, rti commented on lint.sh
> +    npx prettier \"**/*.{cjs,js,json,mjs,ts}\" --write \
This actually brings me back to "linting should be handled outside of test on the root of our project". Then it makes sense again I think.

2024-03-25 12:32 UTC, merged