chore(test): move queryservice tests out of repo
wmde/wikibase-release-pipeline pull request #667
Opened 2024-04-24 15:08 UTC by rti

2024-04-25 07:33 UTC, lorenjohnson commented
I like it. Tell me more?

2024-04-29 08:12 UTC, RickiJay-WMDE commented on test/suites/queryservice/queryservice.conf.ts
> +	composeFiles: [ ...defaultTestSettings.composeFiles ]
Should default to exactly that if you leave out the `composeFiles` argument entirely

2024-04-29 12:46 UTC, RickiJay-WMDE requested changes

2024-06-10 08:00 UTC, rti commented
not really interesting, tests restructuring is not a current focus

2024-06-10 08:00 UTC, closed without merging